Build: Enable build config build feature for wordpress utils
This is an AGP version '8.0' breaking change that changes the build
option default values, see build failure below:

------------------------------------------------------------------------

> Task :WordPressUtils:compileDebugJavaWithJavac FAILED
/Users/.../WordPressUtils/src/main/java/org/wordpress/android/
util/PackageUtils.java:12: error: cannot find symbol
        return BuildConfig.DEBUG;
               ^
  symbol:   variable BuildConfig
  location: class PackageUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/.../WordPressUtils/src/main/java/org/wordpress/android/
util/JSONUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WordPressUtils:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

------------------------------------------------------------------------

Explanation: "Starting with AGP 8.0, the default values for these flags
have changed to improve build performance. AGP 8.0 doesn't generate
'BuildConfig' by default. You need to specify this option using the DSL
in the projects where you need it."

For more info see: https://developer.android.com/build/releases/
gradle-plugin#default-changes