Build: Update kotlin to 1.6.10
This update isn't that necessary, but should be considered anyway as it
will do the following:
- Align this library, to that Kotlin version, which is already used by
most of this library's clients and libraries.
- Fix the 'NoClassDefFoundError' non-fatal error while assembling the
build and more specifically while running the 'compileKotlin' task, see
below exception:

------------------------------------------------------------------------

> Task :WordPressUtils:compileDebugKotlin
Compilation with Kotlin compile daemon was not successful
java.rmi.ServerError: Error occurred in server thread; nested exception
is: java.lang.NoClassDefFoundError: Could not initialize class
org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch
            (UnicastServerRef.java:389)
        ...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class
org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil
        at org.jetbrains.kotlin.com.intellij.util.io
            .ReadWriteDirectBufferWrapper$FileContext$1.execute
            (ReadWriteDirectBufferWrapper.java:59)
        ...
        ... 3 more

------------------------------------------------------------------------